### PR TITLE
Update documentation, php version

### PR DESCRIPTION
**Pull request by castastrophe**
- Added contributors
- Updated supported PHP version to 7.1
- Add new URL to README

### CODE REVIEW

**Comment by castastrophe** [comment]
@starryeyez024 bump

**Comment by starryeyez024** [comment]
Weird, sorry I swear I tried to leave a comment on this a few weeks ago. I'm not a big fan of this change because it would break existing bookmark links people have, and we've been getting a lot of traction with folks using patternkit lately! Which is awesome! So I don't want to set anyone backwards.

**Comment by castastrophe** [comment]
@starryeyez024 Sure, I definitely understand that.  I was just thinking that the URL would be more intuitive without the word `schema` in the path since the bulk of site users won't be familiar with what a schema is.  We could possible set up a redirect for both?  Would that be a good compromise?

**Comment by castastrophe** [comment]
In the meantime, I just updated this to be the php version and documentation update

**Pull request merged**
