### PR TITLE
WIP Update bootstrap and styles

### PR DESCRIPTION
**Pull request by castastrophe**
Instructions for testing:

In the repository using PatternKit (webrh for example), update the composer.json file to:
```
    "require": {
        "pattern-builder/pattern-kit": "*"
    }
```
```
repositories": [{
      "type": "path",
      "url": "/Users/carobert/Projects/pattern-kit",
      "options": {
        "symlink": true
      }
    }, {
      "type": "vcs",
      "url": "https://github.com/PatternBuilder/pattern-kit"
}]
```
^ Put your local path to pattern-kit repository here

Run `rm composer.lock && composer require pattern-builder/pattern-kit @dev`.
Kick off the watch task (`npm run watch`)

### CODE REVIEW

**Comment by castastrophe** [comment]
Instructions for testing:

1. In the repository using PatternKit (webrh for example), update the composer.json file to:

```json
    "require": {
        "pattern-builder/pattern-kit": "*"
    }
```

```json"
repositories": [{
      "type": "path",
      "url": "/Users/carobert/Projects/pattern-kit",
      "options": {
        "symlink": true
      }
    }, {
      "type": "vcs",
      "url": "https://github.com/PatternBuilder/pattern-kit"
}]
```

^ Put your local path to pattern-kit repository here

2. Run `rm composer.lock && composer require pattern-builder/pattern-kit @dev`.
3. Kick off the watch task (`npm run watch`)

**Comment by castastrophe** [comment]
If that testing process doesn't work ^ you can also just copy the folders from the pattern-kit repo into the vendors directory in webrh. 🤷‍♀

**Comment by castastrophe** [comment]
This branch needs some clean-up for styles.

**Comment by starryeyez024** [comment]
@castastrophe   maybe this could be split up into a few smaller PRs:

1. JSON editor styles
2. Menu / Styleguide styles
3. Update URL button functionality 

I'm seeing a handful of issues:

- If I copy the contents of PK into webrh, I get an error. If I only copy `web` and `resources` it kind of works. Copying `src` creates an error.  I also tried re-running `composer install` and then copying.. no luck. Not sure if I'm testing correctly or if theres an easier way.
    ```
    Fatal error: Uncaught Error: Call to undefined method PatternKit\Model\PatternModel::get_asset_path() in /Users/ktotten/Sites/webrh/vendor/pattern-builder/pattern-kit/src/app.php:101 Stack trace: #0 /Users/ktotten/Sites/webrh/vendor/pattern-builder/pattern-kit/src/app.php(97): data_replace(Array) #1 /Users/ktotten/Sites/webrh/vendor/pattern-builder/pattern-kit/src/PatternKit/Model/PatternModel.php(72): data_replace(Array) #2 /Users/ktotten/Sites/webrh/vendor/pattern-builder/pattern-kit/src/PatternKit/SchemaControllerProvider.php(51): PatternKit\Model\PatternModel->getSeedData() #3 [internal function]: PatternKit\SchemaControllerProvider->PatternKit\{closure}('pattern_page') #4 /Users/ktotten/Sites/webrh/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #5 /Users/ktotten/Sites/webrh/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Reque in /Users/ktotten/Sites/webrh/vendor/pattern-builder/pattern-kit/src/app.php on line 101
    ```
- I see the link is correctly generated in the "Update URL" button href, but clicking the button does not refresh the page with that URL or copy to the clipboard.
- Bootstrap styles cause the styleguide left nav to wrap, might need something like:
    ```
    .nav {
        flex-direction: column;
    }
    .nav-tabs {
        flex-direction: row;
    }
    ```
- The preview of where components or patterns should be isn't working correctly; components are cut off
- The new font awesome CSS doesn't seem to  work, I'm just getting empty brackets where icons should be
- We might want to update from Overpass to Red Hat Text?

**Comment by starryeyez024** [comment]
sorry, just saw that testing instructions are in a comment (I just saw the empty description), however this:
```
repositories": [{
      "type": "path",
      "url": "/Users/carobert/Projects/pattern-kit",
      "options": {
        "symlink": true
      }
    }, {
      "type": "vcs",
      "url": "https://github.com/PatternBuilder/pattern-kit"
}]
```
 doesn't match the syntax of the composer file?

**Comment by castastrophe** [comment]
@starryeyez024 I wouldn’t spend much time on this. I merged master into it and it broke a lot of the work I had done because there were so many changes. 😢

**Comment by starryeyez024** [comment]
@castastrophe doh! Could we still salvage the Update URL button? That is super useful!

**Comment by starryeyez024** [comment]
Also that's weird, I only see one very small commit in Dec 2019 to this repo? https://github.com/PatternBuilder/pattern-kit/commits/master

**Pull request closed without merging**
