### PR TITLE
Feature/jassmith/refactor and per module assets

### PR DESCRIPTION
**Pull request by SiliconValet**
Refactor of pattern kit, additions to component renderer
    * Factored methods out of large controllers.
    * Removed redundant code
    * Added a pattern model class to abstract the patterns a bit.
    * Modified the way webcomponent renderer works.
    * Added style component server.
    * Changed from lzstring to pako for more portability across platforms (lzstring sucks at reproducibility cross-platform)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
Yeah! Someone is finally cleaning up my crappy old code :D If you see something and think "wow thats a horrible hack!", yes it was. This was my first (and probably last) php project of this scale. Thanks for giving it some polish.

**Comment by SiliconValet** [comment]
I've got plenty of my own mess in there now, blame is slowly becoming mine.

Great concepts in there, works great as a dynamic templating engine. Most of what I've done with it is just housekeeping and stuff to extend the RESTful stuff. Thanks for the hard work!

**Comment by micahgodbolt** [comment]
I'm glad someone is enjoying and appreciating it! Have you heard about the movement in PHP pattern lab to introduce some of the same ideas? They specifically reference this project.

**Comment by SiliconValet** [comment]
yeah, Derek Reese is driving a lot of that and some of those ideas are
coming from this effort.

**Comment by castastrophe** [comment]
@SiliconValet & @micahgodbolt It seems like this MR is getting a little stale.  I'm wondering what state of review this MR is in?  Is it close to being mergeable?  Does it change any functionality and if so, should we tie it to a major release?

**Comment by micahgodbolt** [comment]
I'm not really in a position to review it at the moment.

**Comment by castastrophe** [comment]
@micahgodbolt Understandable!  I just saw you were in the discussion so I wanted to cc you.  I was more asking @SiliconValet to see where this was in review.

**Comment by micahgodbolt** [comment]
Thanks :)

**Comment by starryeyez024** [comment]
@SiliconValet can you provide testing & setup instructions?

**Comment by ThatGuyCND** [comment]
@SiliconValet used [`composer-link`](https://johannespichler.com/add-composer-link-command/) to test this locally with WebRH's PK implementation. Everything works as expected. I would say that this PR is **ready to merge**.

**Pull request merged**
